/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  EventEmitter,
} from '@stencil/core';


export namespace Components {

  interface SuperTabButton {
    'disabled': boolean;
    'index': number;
  }
  interface SuperTabButtonAttributes extends StencilHTMLAttributes {
    'disabled'?: boolean;
    'index'?: number;
    /**
    * Emitted when the button loses focus.
    */
    'onIonBlur'?: (event: CustomEvent<void>) => void;
    /**
    * Emitted when the button has focus.
    */
    'onIonFocus'?: (event: CustomEvent<void>) => void;
  }

  interface SuperTab {
    'index': number;
  }
  interface SuperTabAttributes extends StencilHTMLAttributes {
    'index'?: number;
    /**
    * Emitted when the button loses focus.
    */
    'onIonBlur'?: (event: CustomEvent<void>) => void;
  }

  interface SuperTabsContainer {
    'index': number;
  }
  interface SuperTabsContainerAttributes extends StencilHTMLAttributes {
    'index'?: number;
    'onIonTouchEnd'?: (event: CustomEvent<TouchEvent>) => void;
    'onIonTouchMove'?: (event: CustomEvent<TouchEvent>) => void;
    'onIonTouchStart'?: (event: CustomEvent<TouchEvent>) => void;
  }

  interface SuperTabsToolbar {
    'index': number;
    'toolbarPosition': 'top' | 'bottom';
  }
  interface SuperTabsToolbarAttributes extends StencilHTMLAttributes {
    'index'?: number;
    /**
    * Emitted when the button loses focus.
    */
    'onIonBlur'?: (event: CustomEvent<void>) => void;
    'toolbarPosition'?: 'top' | 'bottom';
  }

  interface SuperTabs {
    'index': number;
  }
  interface SuperTabsAttributes extends StencilHTMLAttributes {
    'index'?: number;
    /**
    * Emitted when the button loses focus.
    */
    'onIonBlur'?: (event: CustomEvent<void>) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SuperTabButton': Components.SuperTabButton;
    'SuperTab': Components.SuperTab;
    'SuperTabsContainer': Components.SuperTabsContainer;
    'SuperTabsToolbar': Components.SuperTabsToolbar;
    'SuperTabs': Components.SuperTabs;
  }

  interface StencilIntrinsicElements {
    'super-tab-button': Components.SuperTabButtonAttributes;
    'super-tab': Components.SuperTabAttributes;
    'super-tabs-container': Components.SuperTabsContainerAttributes;
    'super-tabs-toolbar': Components.SuperTabsToolbarAttributes;
    'super-tabs': Components.SuperTabsAttributes;
  }


  interface HTMLSuperTabButtonElement extends Components.SuperTabButton, HTMLStencilElement {}
  var HTMLSuperTabButtonElement: {
    prototype: HTMLSuperTabButtonElement;
    new (): HTMLSuperTabButtonElement;
  };

  interface HTMLSuperTabElement extends Components.SuperTab, HTMLStencilElement {}
  var HTMLSuperTabElement: {
    prototype: HTMLSuperTabElement;
    new (): HTMLSuperTabElement;
  };

  interface HTMLSuperTabsContainerElement extends Components.SuperTabsContainer, HTMLStencilElement {}
  var HTMLSuperTabsContainerElement: {
    prototype: HTMLSuperTabsContainerElement;
    new (): HTMLSuperTabsContainerElement;
  };

  interface HTMLSuperTabsToolbarElement extends Components.SuperTabsToolbar, HTMLStencilElement {}
  var HTMLSuperTabsToolbarElement: {
    prototype: HTMLSuperTabsToolbarElement;
    new (): HTMLSuperTabsToolbarElement;
  };

  interface HTMLSuperTabsElement extends Components.SuperTabs, HTMLStencilElement {}
  var HTMLSuperTabsElement: {
    prototype: HTMLSuperTabsElement;
    new (): HTMLSuperTabsElement;
  };

  interface HTMLElementTagNameMap {
    'super-tab-button': HTMLSuperTabButtonElement
    'super-tab': HTMLSuperTabElement
    'super-tabs-container': HTMLSuperTabsContainerElement
    'super-tabs-toolbar': HTMLSuperTabsToolbarElement
    'super-tabs': HTMLSuperTabsElement
  }

  interface ElementTagNameMap {
    'super-tab-button': HTMLSuperTabButtonElement;
    'super-tab': HTMLSuperTabElement;
    'super-tabs-container': HTMLSuperTabsContainerElement;
    'super-tabs-toolbar': HTMLSuperTabsToolbarElement;
    'super-tabs': HTMLSuperTabsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
